name: sync
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no saved creds, full history)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config user.name "chelaran-sync-bot"
          git config user.email "actions@github.com"

      - name: Verify access
        run: |
          git ls-remote https://bambutcha:${{ secrets.BAMBUTCHA_PERSONAL_TOKEN }}@github.com/bambutcha/yagalog.git

      - name: Push master to personal mirror (exclude .github)
        run: |
          rm -rf /tmp/mirror
          mkdir -p /tmp/mirror
          git --work-tree=/tmp/mirror checkout -f
          rm -rf /tmp/mirror/.github
          cd /tmp/mirror
          git init
          git config user.name "chelaran-sync-bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "mirror snapshot"
          git branch -M master
          git remote add personal https://bambutcha:${{ secrets.BAMBUTCHA_PERSONAL_TOKEN }}@github.com/bambutcha/yagalog.git
          git push personal master --force